- name: Get bastion node facts
  ec2_instance_facts:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    aws_region: '{{ aws_region }}'
    filters:
      "tag:Type": '{{ bastion_type }}'
      instance-state-name: ["running"]
  register: bastion_nodes

- name: Get the IP address of the bastion
  set_fact:
    bastion_public_ip: '{{ bastion_nodes.instances[0].public_ip_address }}'

- name: 'Get {{ node_type }} nodes'
  ec2_instance_facts:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    aws_region: '{{ aws_region }}'
    filters:
      "tag:Type": '{{ node_type }}'
      instance-state-name: ["running"]
  register: nodes

- name: 'Create the {{ group_name }} group'
  add_host:
    name: '{{ item.instance_id }}'
    group: '{{ group_name }}'
    instance_id: '{{ item.instance_id }}'
    ansible_host: '{{ item.network_interfaces[0].private_ip_address }}'
    ansible_ssh_private_key_file: ./output/kube.pem
    ansible_ssh_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ./output/kube.pem -q ubuntu@{{ bastion_public_ip }} -o StrictHostKeyChecking=no"'
  loop: '{{ nodes.instances }}'