---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Description: Name of the project
    Type: String
  MasterAutoScalingGroupName:
    Description: Name of the AutoScalingGroup
    Type: String
  WorkerAutoScalingGroupName:
    Description: Name of the AutoScalingGroup
    Type: String
  LaunchTemplateName:
    Description: Name of the LaunchTemplate
    Type: String
  SecurityGroup:
    Description: Security Group ID
    Type: String
  KeyName:
    Description: SSH Key
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: EC2 Instance type
    Type: String
    Default: m5.large
  ImageId:
    Description: Instance ImageId
    Type: String
    Default: ami-064a0193585662d74
  VolumeSize:
    Type: Number
    Description: Node volume size.
    Default: 20
  MasterDesiredCapacity:
    Type: Number
    Description: Master nodes desired capacity
    Default: 3
  WorkerDesiredCapacity:
    Type: Number
    Description: Worker nodes desired capacity
    Default: 3
  MaxSize:
    Type: Number
    Description: Cluster max capacity
    Default: 8
  MinSize:
    Type: Number
    Description: Cluster min capacity
    Default: 1
  PrivateSubnetIdA:
    Type: String
    Description: Private Subnet A Id
  PrivateSubnetIdB:
    Type: String
    Description: Private Subnet B Id
  PrivateSubnetIdC:
    Type: String
    Description: Private Subnet C Id
  PublicSubnetIdA:
    Type: String
    Description: Public Subnet A Id
  PublicSubnetIdB:
    Type: String
    Description: Public Subnet B Id
  PublicSubnetIdC:
    Type: String
    Description: Public Subnet C Id
  NetworkLoadBalancerName:
    Type: String
    Description: Network Load Balancer Name
  VpcId:
    Type: String
    Description: VPC ID
Resources:
  
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref SecurityGroup
  
  WorkerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: !Ref WorkerDesiredCapacity
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      VPCZoneIdentifier:
        - !Ref PrivateSubnetIdA
        - !Ref PrivateSubnetIdB
        - !Ref PrivateSubnetIdC
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification: 
            LaunchTemplateId: !Ref LaunchTemplate
            Version: 1
          Overrides:
            - InstanceType: m5.large
            - InstanceType: m4.large
            - InstanceType: m3.large
            - InstanceType: t3.xlarge
            - InstanceType: t2.xlarge
            - InstanceType: t3.2xlarge
            - InstanceType: t2.2xlarge
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: lowest-price
          SpotInstancePools: 4
      Tags:
        - Key: Name
          Value: !Ref WorkerAutoScalingGroupName
          PropagateAtLaunch: 'true'
        - Key: Project
          Value: !Ref ProjectName
          PropagateAtLaunch: 'true'
        - Key: Type
          Value: worker
          PropagateAtLaunch: 'true'

  MasterAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: !Ref MasterDesiredCapacity
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      TargetGroupARNs:
        - !Ref KubernetesAPITargetGroup
      VPCZoneIdentifier:
        - !Ref PrivateSubnetIdA
        - !Ref PrivateSubnetIdB
        - !Ref PrivateSubnetIdC
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification: 
            LaunchTemplateId: !Ref LaunchTemplate
            Version: 1
          Overrides:
            - InstanceType: t3.small
            - InstanceType: t3.medium
            - InstanceType: m5.large
            - InstanceType: m4.large
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: lowest-price
          SpotInstancePools: 4
      Tags:
        - Key: Name
          Value: !Ref MasterAutoScalingGroupName
          PropagateAtLaunch: 'true'
        - Key: Project
          Value: !Ref ProjectName
          PropagateAtLaunch: 'true'
        - Key: Type
          Value: master
          PropagateAtLaunch: 'true'

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Ref NetworkLoadBalancerName
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
        - !Ref PublicSubnetIdC
      Type: network
      Tags:
        - Key: Name
          Value: !Ref NetworkLoadBalancerName
        - Key: Project
          Value: !Ref ProjectName

  Listener443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref KubernetesAPITargetGroup
          Type: forward
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 443
      Protocol: TCP
  
  KubernetesAPITargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckPort: 6443
      HealthCheckProtocol: HTTPS
      HealthCheckPath: /healthz
      HealthCheckEnabled: true
      Name: KubernetesAPITargetGroup
      Port: 6443
      Protocol: TCP
      VpcId: !Ref VpcId
      Tags:  
        - Key: Name
          Value: KubernetesAPITargetGroup
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  NetworkLoadBalancerDNSName:
    Description: ALB DNS Name
    Value: !GetAtt NetworkLoadBalancer.DNSName
  NetworkLoadBalancerCanonicalHostedZoneID:
    Description: ALB Canonical Hosted Zone ID
    Value: !GetAtt NetworkLoadBalancer.CanonicalHostedZoneID