---
- name: Create the infraestructure
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - ./secret.yml
  vars:
    state: present
  roles:
    - assert_requirements
    - infrastructure
    - create_dynamic_groups
    - create_certificates
    - create_kubeconfigs
    - configure_private_route_table

- name: Configure the master nodes
  hosts: masters
  gather_facts: no
  vars_files:
    - secret.yml
  roles:
    - configure_servers
    - create_etcd_cluster
    - bootstrap_kubernetes_masters

- name: Configure the worker nodes
  hosts: workers
  gather_facts: no
  serial: 1
  vars_files:
    - secret.yml
  roles:
    - configure_servers
    - create_worker_certificates
    - create_worker_kubeconfigs

- name: Configure the worker nodes
  hosts: workers
  gather_facts: no
  vars_files:
    - secret.yml
  roles:
    - bootstrap_kubernetes_workers

- name: Configure the Kubernetes cluster
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - ./secret.yml
  roles:
    - kubernetes_configuration