- name: Create Network Cloudformation Stack
  cloudformation:
    stack_name: "{{ project_name }}-networking"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    template: './cloudformation/networking.yaml'
    disable_rollback: true
    template_parameters:
      KubernetesClusterName: '{{ project_name }}'
    tags:
      Name: "{{ project_name }}_bastion"
      Project: "{{ project_name }}"
  register: networking

- name: Save Cloudformation Networking Output
  copy:
    content: "{{ networking | to_nice_yaml }}"
    dest: "./output/networking.yaml"

- name: Create the EC2 Key
  ec2_key:
    name: '{{ key_name }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ aws_region }}'
    state: present
  register: ec2_key

- name: Save EC2 key
  copy:
    content: '{{ ec2_key.key.private_key }}'
    dest: './output/{{ key_name }}.pem'
    mode: '0400'
  when: ec2_key.key.private_key is defined

- name: Create the Bastion Instance
  cloudformation:
    stack_name: '{{ project_name }}-bastion-instance'
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    template: './cloudformation/instance.yaml'
    disable_rollback: true
    template_parameters:
      InstanceName: '{{ aws_bastion_name }}'
      SecurityGroup: '{{ networking.stack_outputs.SecurityGroupId }}'
      KeyName: '{{ key_name }}'
      InstanceType: '{{ aws_bastion_instance_type }}'
      ImageId: '{{ image_id }}'
      SubnetId: '{{ networking.stack_outputs.PublicSubnet3 }}'
  register: instance

- name: Save Cloudformation Instance Output
  copy:
    content: "{{ instance | to_nice_yaml }}"
    dest: "./output/instance.yaml"

- name: Create Cloudformation Auto Scaling Groups Stacks
  cloudformation:
    stack_name: "{{ project_name }}-auto-scaling-group"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    template: './cloudformation/auto_scaling_group.yaml'
    disable_rollback: true
    template_parameters:
      ProjectName: '{{ project_name }}'
      MasterAutoScalingGroupName: '{{ aws_master_asg_name }}'
      WorkerAutoScalingGroupName: '{{ aws_worker_asg_name }}'
      LaunchTemplateName: '{{ aws_lt_name }}'
      SecurityGroup: '{{ networking.stack_outputs.SecurityGroupId }}'
      KeyName: '{{ key_name }}'
      InstanceType: '{{ aws_default_instance_type }}'
      ImageId: '{{ image_id }}'
      VolumeSize: '{{ aws_volume_size }}'
      MasterDesiredCapacity: '{{ aws_master_asg_desired_capacity }}'
      WorkerDesiredCapacity: '{{ aws_worker_asg_desired_capacity }}'
      MinSize: '{{ aws_asg_min_size }}'
      MaxSize: '{{ aws_asg_max_size }}'
      PrivateSubnetIdA: '{{ networking.stack_outputs.PrivateSubnet0 }}'
      PrivateSubnetIdB: '{{ networking.stack_outputs.PrivateSubnet1 }}'
      PrivateSubnetIdC: '{{ networking.stack_outputs.PrivateSubnet2 }}'
      PublicSubnetIdA: '{{ networking.stack_outputs.PublicSubnet3 }}'
      PublicSubnetIdB: '{{ networking.stack_outputs.PublicSubnet4 }}'
      PublicSubnetIdC: '{{ networking.stack_outputs.PublicSubnet5 }}'
      NetworkLoadBalancerName: '{{ aws_nlb_name }}'
      VpcId: '{{ networking.stack_outputs.VpcId }}'
  register: auto_scaling_group

- name: Save Cloudformation Auto Scaling Group Output
  copy:
    content: "{{ auto_scaling_group | to_nice_yaml }}"
    dest: "./output/auto_scaling_group.yaml"

- name: Create the DNS record for the Kubernetes API Load Balancer
  route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    overwrite: true
    state: present
    zone: '{{ public_domain }}'
    record: '{{ kubernetes_api_public_uri }}'
    type: A
    value: '{{ auto_scaling_group["stack_outputs"]["NetworkLoadBalancerDNSName"] }}'
    alias: True
    alias_hosted_zone_id: '{{ auto_scaling_group["stack_outputs"]["NetworkLoadBalancerCanonicalHostedZoneID"] }}'