- name: Check that the worker kubeconfig exists
  delegate_to: localhost
  stat:
    path: '{{ kubeconfigs_folder }}/{{ instance_id }}.kubeconfig'
  register: kubeconfig

- name: Create the kubeconfig files for each worker node
  delegate_to: localhost
  shell: >
    kubectl config set-cluster {{ project_name }} \
      --certificate-authority={{ certificates_folder }}/ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes_api_public_uri }} \
      --kubeconfig={{ kubeconfigs_folder }}/{{ instance_id }}.kubeconfig ;\
    
    kubectl config set-credentials system:node:{{ instance_id }} \
      --client-certificate={{ certificates_folder }}/{{ instance_id }}.pem \
      --client-key={{ certificates_folder }}/{{ instance_id }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ kubeconfigs_folder }}/{{ instance_id }}.kubeconfig ;\
    
    kubectl config set-context default \
      --cluster={{ project_name }} \
      --user=system:node:{{ instance_id }} \
      --kubeconfig={{ kubeconfigs_folder }}/{{ instance_id }}.kubeconfig ;\
    
    kubectl config use-context default \
      --kubeconfig={{ kubeconfigs_folder }}/{{ instance_id }}.kubeconfig
  when: kubeconfig.stat.exists == False