---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Description: Name of the project
    Type: String
  AutoScalingGroupName:
    Description: Name of the AutoScalingGroup
    Type: String
  LaunchTemplateName:
    Description: Name of the LaunchTemplate
    Type: String
  SecurityGroup:
    Description: Security Group ID
    Type: String
  KeyName:
    Description: SSH Key
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: EC2 Instance type
    Type: String
    Default: m5.large
  ImageId:
    Description: Instance ImageId
    Type: String
    Default: ami-064a0193585662d74
  VolumeSize:
    Type: Number
    Description: Node volume size.
    Default: 20
  DesiredCapacity:
    Type: Number
    Description: Cluster desired capacity
    Default: 3
  MaxSize:
    Type: Number
    Description: Cluster max capacity
    Default: 8
  MinSize:
    Type: Number
    Description: Cluster min capacity
    Default: 1
  SubnetIdA:
    Type: String
    Description: Subnet A Id
  SubnetIdB:
    Type: String
    Description: Subnet B Id
  SubnetIdC:
    Type: String
    Description: Subnet C Id
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref LaunchTemplateName
      LaunchTemplateData:
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref SecurityGroup
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: !Ref DesiredCapacity
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      VPCZoneIdentifier:
        - !Ref SubnetIdA
        - !Ref SubnetIdB
        - !Ref SubnetIdC
      MixedInstancesPolicy:
        LaunchTemplate:
          LaunchTemplateSpecification: 
            LaunchTemplateId: !Ref LaunchTemplate
            Version: 1
          Overrides:
            - InstanceType: m5.large
            - InstanceType: m4.large
            - InstanceType: m3.large
            - InstanceType: t3.xlarge
            - InstanceType: t2.xlarge
            - InstanceType: t3.2xlarge
            - InstanceType: t2.2xlarge
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: lowest-price
          SpotInstancePools: 4
      Tags:
        - Key: Name
          Value: !Ref AutoScalingGroupName
          PropagateAtLaunch: 'true'
        - Key: Project
          Value: !Ref ProjectName
          PropagateAtLaunch: 'true'
        - Key: Worker
          Value: true
          PropagateAtLaunch: 'true'
        - Key: Master
          Value: true
          PropagateAtLaunch: 'true'
        - Key: Infra
          Value: true
          PropagateAtLaunch: 'true'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: '1'
        MinInstancesInService: !Ref DesiredCapacity
        PauseTime: 'PT5M'