networking_stack_name: '{{ project_name }}-networking'
bastion_stack_name: '{{ project_name }}-bastion'
bastion_instance_name: '{{ project_name }}-bastion-instance'
bastion_instance_type: t3.small
asg_stack_name: '{{ project_name }}-asg'
asg_default_instance_type: m5.large
asg_volume_size: 100
master_asg_desired_capacity: 3
worker_asg_desired_capacity: 3
asg_min_size: 1
asg_max_size: 8
nlb_name: '{{ project_name }}-nlb'
kubernetes_api_public_url: 'k8s.{{ public_domain }}'