- name: Check that the worker kubeconfig exists
  stat:
    path: './kubeconfigs/{{ item.instance_id }}.kubeconfig'
  register: kubeconfig

- name: Create the kubeconfig files for each worker node
  shell: >
    kubectl config set-cluster {{ project_name }} \
      --certificate-authority=./tls/ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes_api_public_uri }} \
      --kubeconfig=./kubeconfigs/{{ item.instance_id }}.kubeconfig ;\
    
    kubectl config set-credentials system:node:{{ item.instance_id }} \
      --client-certificate=./tls/{{ item.instance_id }}.pem \
      --client-key=./tls/{{ item.instance_id }}-key.pem \
      --embed-certs=true \
      --kubeconfig=./kubeconfigs/{{ item.instance_id }}.kubeconfig ;\
    
    kubectl config set-context default \
      --cluster={{ project_name }} \
      --user=system:node:{{ item.instance_id }} \
      --kubeconfig=./kubeconfigs/{{ item.instance_id }}.kubeconfig ;\
    
    kubectl config use-context default \
      --kubeconfig=./kubeconfigs/{{ item.instance_id }}.kubeconfig
  when: kubeconfig.stat.exists == False
