- name: Copy the instances json certificate request
  template:
    src: ./templates/client-csr.json
    dest: './tls/{{ item.instance_id }}-csr.json'
    mode: '0644'

- name: Check that the {{ item.instance_id }}-key.pem exists
  stat:
    path: './tls/{{ item.instance_id }}-key.pem'
  register: client_key

- name: Check that the worker.pem exists
  stat:
    path: './tls/{{ item.instance_id }}.pem'
  register: client

- name: Generate the client certificate and private key
  shell: >
    cfssl gencert \
      -ca=./tls/ca.pem \
      -ca-key=./tls/ca-key.pem \
      -config=./tls/ca-config.json \
      -hostname={{ item.instance_id }},{{ item.network_interfaces[0].private_ip_address }} \
      -profile=kubernetes \
      ./tls/{{ item.instance_id }}-csr.json | cfssljson -bare ./tls/{{ item.instance_id }}
  when: client_key.stat.exists == False and client.stat.exists == False
