- name: Check that the worker kubeconfig exists
  stat:
    path: './kubeconfigs/{{ item.instance_id }}.kubeconfig'
  register: kubeconfig

- name: Create the kubeconfig files for each worker node
  shell: >
    kubectl config set-cluster {{ project_name }} \
      --certificate-authority=./tls/ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes_api_public_uri }} \
      --kubeconfig=./kubeconfigs/{{ item.instance_id }}
  when: kubeconfig.stat.exists == False