- set_fact:
    key_name: '{{ key_name | default(project_name) }}'

- name: Delete the Bastion Instance
  cloudformation:
    stack_name: '{{ project_name }}-bastion-instance'
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: absent
    region: "{{ aws_region }}"
    template: './cloudformation/instance.yaml'
    disable_rollback: true

- name: Delete Cloudformation Instance Output
  file:
    state: absent
    path: './output/instance.yaml'

- name: Create Cloudformation Instances Stacks
  cloudformation:
    stack_name: "{{ project_name }}-auto-scaling-group"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: absent
    region: "{{ aws_region }}"
    template: './cloudformation/auto_scaling_group.yaml'
    disable_rollback: true

- name: Delete the Auto Scaling Group output
  file:
    state: absent
    path: './output/auto_scaling_group.yaml'

- name: Delete the EC2 Key
  ec2_key:
    name: '{{ key_name }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ aws_region }}'
    state: absent

- name: Delete the private key
  file:
    state: absent
    path: './output/{{ key_name }}.pem'
  when: state == "absent"

- name: Delete Cloudformation Instances Output
  file:
    state: absent
    path: "./output/instance.yaml"

- name: Delete Cloudformation Networking Stack
  cloudformation:
    stack_name: "{{ project_name }}-networking"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: absent
    region: "{{ aws_region }}"
    template: './cloudformation/networking.yaml'
    disable_rollback: true
  register: networking

- name: Delete Cloudformation Networking Output
  file:
    state: absent
    path: "./output/networking.yaml"