---
- name: Create Kubernetes Cluster
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - up
  vars_files:
    - ./secret.yml
  tasks:
    - include_tasks: './tasks/up.yaml'
      when: state == 'present'

- name: Create the Master group
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  vars:
    node_type: master
    group_name: masters
  roles:
    - create_dynamic_node_group

- name: Create the Worker group
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  vars:
    node_type: worker
    group_name: workers
  roles:
    - create_dynamic_node_group

- name: Configure the servers
  hosts: 
    - masters
    - workers
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - name: 'Create the DNS entry for the {{ instance_id }} node'
      delegate_to: localhost
      route53:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: '{{ state }}'
        zone: '{{ private_domain }}'
        record: '{{ instance_id }}.{{ private_domain }}'
        type: A
        ttl: 7200
        value: '{{ ansible_host }}'
        wait: yes
        private_zone: yes

- name: Delete Kubernetes Cluster
  hosts: local
  connection: local
  gather_facts: no
  tags:
    - down
  vars_files:
    - ./secret.yml
  tasks:
    - include_tasks: './tasks/down.yaml'
      when: state != 'present'
