---
- name: Create the Master group
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  vars:
    node_type: master
    group_name: masters
  roles:
    - create_dynamic_node_group

- name: Create the encryption file
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - template:
        src: ./templates/encryption-config.yaml
        dest: './tls/encryption-config.yaml'
        mode: '0644'
      vars:
        secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

- name: Copy the encryption file
  hosts: masters
  gather_facts: no
  vars_files:
    - secret.yml
  tags:
    - copy
  tasks:
    - name: Copy the service-account.pem file
      copy:
        src: ./tls/encryption-config.yaml
        dest: '/home/{{ ansible_ssh_user }}/encryption-config.yaml'
        mode: '0644'