---
- name: Create the Master group
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  vars:
    node_type: master
    group_name: masters
  roles:
    - create_dynamic_node_group
  tasks:
    - set_fact:
        initial_cluster: >
          {{ 
            ( initial_cluster | default([]) )
            + [
              item
              + "="
              + "https://"
              + hostvars[item]["ansible_host"]
              + ":2380"
            ] 
          }}
      loop: '{{ groups["masters"] }}'

    - name: Creating the initial_cluster variable
      add_host:
        name: DUMMY
        initial_cluster: '{{ initial_cluster | join(",") }}'

- name: Create the etcd cluster
  hosts: masters
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - name: Download the etcd Binaries
      get_url:
        url: https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
        dest: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64.tar.gz'
        mode: '0644'

    - name: Make the '/home/{{ ansible_ssh_user }}/etcd' directory
      file:
        state: directory
        path: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64'

    - name: Untar etcd
      unarchive:
        src: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64.tar.gz'
        dest: '/home/{{ ansible_ssh_user }}'
        remote_src: yes
        
    - name: 'Copy the {{ item }} binary to /usr/local/bin/{{ item }}'
      copy:
        src: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64/{{ item }}'
        dest: '/usr/local/bin/{{ item }}'
        mode: '0755'
        remote_src: yes
      become: true
      loop:
        - etcd
        - etcdctl

    - name: 'Make the {{ item }} directory'
      file:
        state: directory
        path: '{{ item }}'
      become: true
      loop:
        - /etc/etcd
        - /var/lib/etcd

    - name: 'Copy {{ item }} to /etc/etcd/'
      copy:
        src: './tls/{{ item }}'
        dest: '/etc/etcd/{{ item }}'
      become: true
      loop:
        - ca.pem
        - kubernetes-key.pem
        - kubernetes.pem

    - name: Create the etcd.service file
      template:
        src: ./templates/etcd.service
        dest: '/etc/systemd/system/etcd.service'
        mode: '0644'
      become: true
      vars:
        initial_cluster: '{{ hostvars["DUMMY"]["initial_cluster"] }}'

    - name: Start the etcd service
      systemd:
        state: started
        daemon_reload: yes
        name: etcd
      become: true




