---
- name: Create the Master group
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  vars:
    node_type: master
    group_name: masters
  tags:
    - inventory
  roles:
    - create_dynamic_node_group
  tasks:
    - set_fact:
        initial_cluster: >
          {{ 
            ( initial_cluster | default([]) )
            + [
              item
              + "="
              + "https://"
              + hostvars[item]["ansible_host"]
              + ":2380"
            ] 
          }}
      loop: '{{ groups["masters"] }}'

    - name: Creating the initial_cluster variable
      add_host:
        name: DUMMY
        initial_cluster: '{{ initial_cluster | join(",") }}'

    - name: Install cfssl
      

- name: Create the etcd cluster
  hosts: masters
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - name: Download the etcd Binaries
      get_url:
        url: https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
        dest: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64.tar.gz'
        mode: '0644'

    - name: Make the '/home/{{ ansible_ssh_user }}/etcd' directory
      file:
        state: directory
        path: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64'

    - name: Untar etcd
      unarchive:
        src: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64.tar.gz'
        dest: '/home/{{ ansible_ssh_user }}'
        remote_src: yes
        
    - name: Copy the etcd binary to /usr/local/bin/etcd
      copy:
        src: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64/etcd'
        dest: /usr/local/bin/etcd
        mode: '0755'
        remote_src: yes
      become: true

    - name: Copy the etcdctl binary to /usr/local/bin/etcd
      copy:
        src: '/home/{{ ansible_ssh_user }}/etcd-v3.3.9-linux-amd64/etcdctl'
        dest: /usr/local/bin/etcdctl
        mode: '0755'
        remote_src: yes
      become: true

    - name: Make the /etc/etcd directory
      file:
        state: directory
        path: '/etc/etcd'
      become: true

    - name: Make the /var/lib/etcd directory
      file:
        state: directory
        path: '/var/lib/etcd'
      become: true

    - name: Copy ca.pem to /etc/etcd/
      copy:
        src: '/home/{{ ansible_ssh_user }}/ca.pem'
        dest: '/etc/etcd/ca.pem'
        remote_src: yes
      become: true

    - name: Copy kubernetes-key.pem to /etc/etcd/
      copy:
        src: '/home/{{ ansible_ssh_user }}/kubernetes-key.pem'
        dest: '/etc/etcd/kubernetes-key.pem'
        remote_src: yes
      become: true

    - name: Copy kubernetes.pem to /etc/etcd/
      copy:
        src: '/home/{{ ansible_ssh_user }}/kubernetes.pem'
        dest: '/etc/etcd/kubernetes.pem'
        remote_src: yes
      become: true

    - name: Create the etcd.service file
      template:
        src: ./templates/etcd.service
        dest: '/etc/systemd/system/etcd.service'
        mode: '0644'
      become: true
      vars:
        initial_cluster: '{{ hostvars["DUMMY"]["initial_cluster"] }}'

    - name: Start the etcd service
      systemd:
        state: started
        daemon_reload: yes
        name: etcd
      become: true




