---
- name: Create the Master group
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  vars:
    node_type: master
    group_name: masters
  tags:
    - inventory
  roles:
    - create_dynamic_node_group
  tasks:
    - set_fact:
        etcd_servers: >
          {{ 
            ( etcd_servers | default([]) )
            + [
              item
              + "="
              + "https://"
              + hostvars[item]["ansible_host"]
              + ":2379"
            ] 
          }}
      loop: '{{ groups["masters"] }}'

    - name: Creating the etcd_servers variable
      add_host:
        name: DUMMY
        etcd_servers: '{{ etcd_servers | join(",") }}'

- name: Create the etcd cluster
  hosts: masters
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - name: Create the Kubernetes configuration directory
      file:
        state: directory
        path: '/etc/kubernetes/config'
      become: true

    - name: Download the kube-apiserver binaries
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-apiserver
        dest: '/usr/local/bin/kube-apiserver'
        mode: '0744'

    - name: Download the kube-controller-manager binaries
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-controller-manager
        dest: '/usr/local/bin/kube-controller-manager'
        mode: '0744'

    - name: Download the kube-scheduler binaries
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-scheduler
        dest: '/usr/local/bin/kube-scheduler'
        mode: '0744'

    - name: Download the kubectl binaries
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl
        dest: '/usr/local/bin/kubectl'
        mode: '0744'

    - name: Create the Kubernetes directory
      file:
        state: directory
        path: '/var/lib/kubernetes'
      become: true

    - name: Copy files to the Kubernetes directory
      copy:
        src: './tls/{{ item }}'
        dest: '/var/lib/kubernetes/{{ item }}'
        mode: '0644'
      become: true
      loop:
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem
        - encryption-config.yaml

    - name: Create the kube-apiserver.service file
      template:
        src: ./templates/kube-apiserver.service
        dest: '/etc/systemd/system/kube-apiserver.service'
        mode: '0644'
      become: true
      vars:
        etcd_servers: '{{ hostvars["DUMMY"]["etcd_servers"] }}'

    - name: Move the kubeconfig files to the Kubernetes directory
      copy:
        src: './kubeconfigs/{{ item }}'
        dest: '/var/lib/kubernetes/{{ item }}'
        mode: '0644'
      become: true
      loop:
        - kube-controller-manager.kubeconfig
    
    - name: Create the kube-controller-manager.service file
      template:
        src: ./templates/kube-controller-manager.service
        dest: '/etc/systemd/system/kube-controller-manager.service'
        mode: '0644'
      become: true
      vars:
        etcd_servers: '{{ hostvars["DUMMY"]["etcd_servers"] }}'

      