---
- name: Kubeconfigs creation
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - name: Get worker nodes
      ec2_instance_facts:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_region: '{{ aws_region }}'
        filters:
          "tag:Type": worker
          instance-state-name: ["running"]
      register: worker_nodes

    - name: Create the kubeconfig files for the worker nodes
      include_tasks: ./tasks/client_kubeconfig.yaml
      loop: '{{ worker_nodes.instances }}'